// <auto-generated />
using HotelManagementSystem.Database;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace HotelManagementSystem.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260614094059_m1")]
    partial class m1
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("GuestStaff", b =>
                {
                    b.Property<int>("StaffId")
                        .HasColumnType("int");

                    b.Property<int>("guestsId")
                        .HasColumnType("int");

                    b.HasKey("StaffId", "guestsId");

                    b.HasIndex("guestsId");

                    b.ToTable("GuestStaff", (string)null);
                });

            modelBuilder.Entity("HotelManagementSystem.Models.Department", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.ToTable("departments");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Description = "first",
                            Name = "Food"
                        },
                        new
                        {
                            Id = 2,
                            Description = "Second",
                            Name = "Wash"
                        });
                });

            modelBuilder.Entity("HotelManagementSystem.Models.Guest", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.ToTable("guests");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Email = "jana@gmail.com",
                            Name = "Jana"
                        },
                        new
                        {
                            Id = 2,
                            Email = "mohammed@gmail.com",
                            Name = "Mohammed"
                        },
                        new
                        {
                            Id = 3,
                            Email = "rawan@gmail.com",
                            Name = "Rawan"
                        });
                });

            modelBuilder.Entity("HotelManagementSystem.Models.Room", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("GuestId")
                        .HasColumnType("int");

                    b.Property<string>("RoomNumber")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.HasIndex("GuestId")
                        .IsUnique();

                    b.HasIndex("RoomNumber")
                        .IsUnique();

                    b.ToTable("rooms");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            GuestId = 1,
                            RoomNumber = "101",
                            Type = "Single"
                        },
                        new
                        {
                            Id = 2,
                            GuestId = 3,
                            RoomNumber = "102",
                            Type = "Single"
                        },
                        new
                        {
                            Id = 3,
                            GuestId = 2,
                            RoomNumber = "103",
                            Type = "Double"
                        });
                });

            modelBuilder.Entity("HotelManagementSystem.Models.Staff", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("DepartmentId")
                        .HasColumnType("int");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("phone")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("DepartmentId");

                    b.ToTable("Staff");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            DepartmentId = 1,
                            Email = "mo3az@gmail.com",
                            Name = "Mo3az",
                            phone = "01234567890"
                        },
                        new
                        {
                            Id = 2,
                            DepartmentId = 1,
                            Email = "mai@gmail.com",
                            Name = "Mai",
                            phone = "01234567890"
                        },
                        new
                        {
                            Id = 3,
                            DepartmentId = 2,
                            Email = "eman@gmail.com",
                            Name = "Eman",
                            phone = "01234567890"
                        });
                });

            modelBuilder.Entity("GuestStaff", b =>
                {
                    b.HasOne("HotelManagementSystem.Models.Staff", null)
                        .WithMany()
                        .HasForeignKey("StaffId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("HotelManagementSystem.Models.Guest", null)
                        .WithMany()
                        .HasForeignKey("guestsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("HotelManagementSystem.Models.Room", b =>
                {
                    b.HasOne("HotelManagementSystem.Models.Guest", "Guest")
                        .WithOne("Room")
                        .HasForeignKey("HotelManagementSystem.Models.Room", "GuestId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Guest");
                });

            modelBuilder.Entity("HotelManagementSystem.Models.Staff", b =>
                {
                    b.HasOne("HotelManagementSystem.Models.Department", "Department")
                        .WithMany("Staff")
                        .HasForeignKey("DepartmentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Department");
                });

            modelBuilder.Entity("HotelManagementSystem.Models.Department", b =>
                {
                    b.Navigation("Staff");
                });

            modelBuilder.Entity("HotelManagementSystem.Models.Guest", b =>
                {
                    b.Navigation("Room")
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
